version: 2.1

orbs:
  pixela: bufferings/pixela@dev:alpha

workflows:
  example:
    jobs:
      - pixela/increment
      - pixela/decrement:
          username: bufferings
          graph-id: orb-example2
