version: 2.1

orbs:
  pixela: bufferings/pixela@0.0.2

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - pixela/increment:
          username: bufferings
          graph-id: orb-example
